### PR TITLE
Add whole-document parsing, try to conform to orgmode syntax draft, generic aeson, add a couple tests

### PR DESCRIPTION
**Pull request by imalsogreg**
Here it is! Tested out with some non-trivial files. I'm sure there are some corner cases to work through but I think this is a good place to check-in, and we can put more thorough tests up (especially cases that we extract from failures on real-world files) as we go.

The last unresolved issue is that matter about whether 
** My headilne  :THESE:THINGS:
Are called keywords or Tags. I got the Tags nomenclature from the orgmode syntax draft, but I wonder if there's some other source that calls them keywords, or if they're commonly called keywords by users and the orgmode syntax draft is out of date. Anyhow, I'm open to tweaking that and would definitely appreciate if you know of other sites that tried to formalize these terms.

Found your orgmode-grammar package - neat :)

### CODE REVIEW

**Comment by ixmatus** [comment]
If you fix the Travis-CI builds before I do (I'll probably get to it later tonight) I'll merge: https://travis-ci.org/digitalmentat/orgmode-parse/builds/56986992

**Comment by imalsogreg** [comment]
All set! Seems like the previous failure was due to travis using 7.4 (despite your 7.6 request in the .travis file).  Anyway, tests passing now.

**Comment by ixmatus** [comment]
Thanks, 7.6 is f'ing old anyway. I'll merge your PR and see about bumping
to 8.x for Travis.
ᐧ

On Fri, Apr 3, 2015 at 1:32 PM, Greg Hale <notifications@github.com> wrote:

> All set! Seems like the previous failure was due to travis using 7.4
> (despite your 7.6 request in the .travis file). Anyway, tests passing now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalmentat/orgmode-parse/pull/2#issuecomment-89384495>
> .
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by ixmatus** [comment]
I'm building right now and will submit to Hackage, thanks for the great PR
:)
ᐧ

On Tue, Apr 7, 2015 at 9:12 AM, Parnell Springmeyer <
parnell@digitalmentat.com> wrote:

> Thanks, 7.6 is f'ing old anyway. I'll merge your PR and see about bumping
> to 8.x for Travis.
> ᐧ
>
> On Fri, Apr 3, 2015 at 1:32 PM, Greg Hale <notifications@github.com>
> wrote:
>
>> All set! Seems like the previous failure was due to travis using 7.4
>> (despite your 7.6 request in the .travis file). Anyway, tests passing now.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/digitalmentat/orgmode-parse/pull/2#issuecomment-89384495>
>> .
>>
>
>
>
> --
> Parnell Springmeyer
> parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
> <http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by imalsogreg** [comment]
Sweet! Thanks for the merge and the tips. :)

**Comment by ixmatus** [comment]
http://www.reddit.com/r/haskell/comments/31r68l/ann_new_release_of_orgmode_parse_010/
ᐧ

On Tue, Apr 7, 2015 at 9:22 AM, Greg Hale <notifications@github.com> wrote:

> Sweet! Thanks for the merge and the tips. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalmentat/orgmode-parse/pull/2#issuecomment-90583432>
> .
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Pull request merged**
