### PR TITLE
Internationalization of the weekday parser.

### PR DESCRIPTION
**Pull request by nushio3**
This patch will make the weekday parser conform to that in the emacs org-mode.
This will allow parsing for non-English weekdays for most locales.

See TODO.org for remaining problems.

### CODE REVIEW

**Comment by nushio3** [comment]
There remains a few flaws to this patch (I won't hide them :) ). As quoted from TODO.org

  At the moment, parserWeekdayTests for some locales are not
  supported, because in such locales the weekdays strings

  - contain characters that are not lexically correct as Haskell strings.
  - contain digits, which should also be rejected by emacs org-mode's parser.

  see test/Weekdays.hs and test/Timestamps.hs .

  Current test for parserWeekdayTests skips such cases. Whether or how
  to support such locales are future work.

**Comment by ixmatus** [comment]
Thank you for the contribution Takayuki! I'm reviewing your pull-requests
tonight and if all is well, will merge them.
ᐧ

On Sat, May 9, 2015 at 2:59 AM, Takayuki Muranushi <notifications@github.com
> wrote:

> There remains a few flaws to this patch (I won't hide them :) ). As quoted
> from TODO.org
>
> At the moment, parserWeekdayTests for some locales are not
> supported, because in such locales the weekdays strings
>
>    - contain characters that are not lexically correct as Haskell strings.
>    -
>
>    contain digits, which should also be rejected by emacs org-mode's
>    parser.
>
>    see test/Weekdays.hs and test/Timestamps.hs .
>
>    Current test for parserWeekdayTests skips such cases. Whether or how
>    to support such locales are future work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalmentat/orgmode-parse/pull/6#issuecomment-100445055>
> .
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by nushio3** [comment]
Nice, please take your time :smile:

**Comment by ixmatus** [comment]
Excellent PR Takayuki, thank you.

**Pull request merged**
