### PR TITLE
updating travis file for 7.10

### PR DESCRIPTION
**Pull request by imalsogreg**

### CODE REVIEW

**Comment by imalsogreg** [comment]
Can I bug you for a Hackage push, too? :D

**Comment by ixmatus** [comment]
Change that bump from a minor to a patch please since we're not changing any APIs, any thing pushed to hackage is just minor bug fixes.

**Comment by imalsogreg** [comment]
Done :)

**Comment by ixmatus** [comment]
New hackage version uploaded along with haddock docs.

**Comment by imalsogreg** [comment]
Much appreciated.

**Pull request merged**
